[mgr]
show_hidden = true

[flavor]
dark = "gruvbox-material"
light = "gruvbox-material"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*"
run  = "git"
group = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*/"
run  = "git"
group = "git"
