onboarding = false

[keys]
prefix = "ctrl+space"

goto = ["alt+j"]

[[keys.command]]
key = "prefix+a"
type = "plugin_action"
command = "nathanflurry.jj-workspace.new"
description = "new jj workspace"

[[keys.command]]
key = "prefix+shift+a"
type = "plugin_action"
command = "nathanflurry.jj-workspace.new-tab"
description = "new jj workspace (in tab)"

[[keys.command]]
key = "prefix+d"
type = "plugin_action"
command = "nathanflurry.jj-workspace.remove"
description = "remove jj workspace"
