# Unbind <C-b> as the prefix key
unbind C-b

# Bind <C-Space> as the prefix key
unbind C-Space
set -g prefix C-Space
bind Space send-prefix

# Mouse
set -g mouse on

# History
set -g history-limit 100000

# Colors
set -g default-terminal "tmux-256color"

# Window navigation
bind -n M-h previous-window
bind -n M-l next-window

# Resizing
bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

# Splits
bind n split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload
bind r source-file ~/.config/tmux/tmux.conf

# Escape
set -sg escape-time 0

# Windows
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Sesh
bind -n M-j display-popup -E -w 40% -h 50% "sesh picker -i"

# Fixes shift enter problems
set -g xterm-keys on
set -as terminal-features ',*:extkeys'
set -s extended-keys always
set -s extended-keys-format csi-u

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '/usr/share/tmux-plugin-manager/tpm'

# vi keys for copy mode
set-window-option -g mode-keys vi

# Bar
set -g status-position top
set -g status-justify absolute-centre
set -g status 2
set -g status-format[1] "#[bg=default] "

set -g status-style "bg=default"

set -g window-status-format " #W "
set -g window-status-current-format " #W "

set -g automatic-rename off
set-window-option -g automatic-rename off

# Melange
set -g status-left "#[fg=#ECE1D7,bg=#403A36,bold] #S #[default]"

set -g window-status-current-style fg='#ECE1D7',bold
set -g window-status-style 'fg=#403A36',bold

set -g pane-border-style fg='#B380B0'
set -g pane-active-border-style fg='#B380B0'

set -g message-style fg='#292522'

set -g display-panes-active-colour '#B380B0'
set -g display-panes-colour '#B380B0'

set -g clock-mode-colour '#B380B0'

set -g mode-style fg='#292522',bg='#403A36'
