[tools]
node = "lts"
bun = "latest"
usage = "latest"
"npm:portless" = "latest"

# cli
neovim = "latest"
jj = "latest"
jjui = "latest"
yazi = "latest"
opencode = "latest"
claude = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
bat = "latest"
eza = "latest"
zoxide = "latest"
jq = "latest"
gh = "latest"
btop = "latest"
herdr = "latest"
pi = "latest"
"github:jorgerojas26/lazysql" = "latest"
"github:agavra/tuicr" = "latest"
